### ISSUE TITLE
Multiple timeseries are not handled

### ISSUE THREAD

**Issue by steffanlm** [JonasPed/pyeloverblik#1]
Hi Jonas,

I'm working with this repository, and it works almost like a charm.
I've never been using Git as developer or contributor before, so sorry for posting like this.
As I have data more than 5 years back in time in DataHub/Eloverblik, I do hit more than one TimeSeries, when requesting all data, hence I've changed a bit of the code in eloverblik.py.

Hope that my code can contribute with something - and I will start looking into how I can contribute directly into your repository.

In the "eloverblik.py", in the _parse_result section, I've changed a bit, to better handle the different values returned. All the data has been re-formatted to fit perfectly into an InfluxDB directly, and to expose some more layers of data, that might be needed to handle multiple meters and data with different resolution level.

I've added my "code" as a txt document, as the format wasn't right after copying it in - sorry for being completely newbie on this matter.

Best regards
Steffan

[eloverblik.txt](https://github.com/JonasPed/pyeloverblik/files/4268651/eloverblik.txt)

**Comment by JonasPed** [comment]
First of all thanks for trying to contribute. I do however see some issues with the code. 
1. Currently the usage of _parse_result is only used by get_yesterday_parsed and it should only return data for a single day. 
2. The data returned is in a completely other format than the current. This means that it will break existing usage. 

What you can do is to call the get_time_series method and then write your own parser as that method returns the entire result. 

If you have contributions to the code base please create them as pull requests.
