### ISSUE TITLE
Code fails if input from_date or to_date is a string

### ISSUE THREAD

**Issue by nielsjansendk** [JonasPed/pyeloverblik#13]
This line assumes that from_date or to_date is a datetime object:

https://github.com/JonasPed/pyeloverblik/blob/1e4103ddcd074a5a8b4126f9b9028d6bd208e978/pyeloverblik/eloverblik.py#L52

But in the README they are input as strings: 

`data = client.get_time_series(METERING_POINT, from_date='2021-01-01', to_date='2021-01-03', aggregation='Hour')`

This will fail. They need to be parsed as datetime before getting to line 52. You could input them as datetime objects, but then the README needs to be updated.

**Comment by JonasPed** [comment]
Thanks. I have updated README.md.
