### ISSUE TITLE
Timezone (Z) fra API  bliver ikke læst korrekt

### ISSUE THREAD

**Issue by schafdog** [JonasPed/pyeloverblik#18]
Hej Jonas 

Dit format til parsning af datoer fra API'et er:
 '%Y-%m-%dT%H:%M:%SZ'  men burde nok være:  
'%Y-%m-%dT%H:%M:%S%z'

Så bliver timezone (Z) parse korrekt og man kan vise dem som  korrekt i lokal tidszone.

**Comment by JonasPed** [comment]
Helt korrekt. Det får jeg rette i https://github.com/JonasPed/pyeloverblik/pull/19.
