### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by Westendahl** [JonasPed/pyeloverblik#2]
Hi Jonas 
Har du evt et eksemplet på og kan man overhoved bruge din extension ifbm et simplet test hvor man henter data fra eloverblik api'et 

Har lige fået en token og ville lige se om jeg kunne trække data på en nem måde

/Jesper

**Comment by JonasPed** [comment]
Hvis du installerer pyeloverblik via pypi bør du kunne køre nedenstående. 
python -m pyeloverblik --refresh-token REFRESH_TOKEN --metering-point=MÅLE_PUNKT
