### ISSUE TITLE
Rate limiting logic

### ISSUE THREAD

**Issue by scaarup** [JonasPed/pyeloverblik#9]
Official API docs for eloverblik (https://api.eloverblik.dk/customerapi/index.html), states the following "If you get an error 429 or 503, wait 1min. before retrying."
This logic is not built into this project. Even if I want to use your wrapper and build my own logic around rate limiting, it is difficult, since you are calling the API multiple times out of my control.
I suggest implementing this logic: if any of your calls get a 429, wait 60 secs and try again.

**Comment by scaarup** [comment]
https://github.com/JonasPed/pyeloverblik/pull/10

**Comment by JonasPed** [comment]
#10 merged.
